name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_requests:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  helloworld:
    runs-on: ubuntu-20.04

    steps:
      - name: Greetings from Github Actions
        shell: python
        run: |
          print("Hello World")

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setting up correct Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python package and requirements
        run: |
          python -m pip install .
          python -m pip install -r requirements-dev.txt

      - name: Run Python test
        run: |
          pytest
