name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  testing:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - windows-2022
          - macos-11
        python-version:
          - 3.8
          - 3.9

    runs-on: ${{ matrix.os }}
    name: Testing on ${{ matrix.os }}

    steps:
      - name: Greetings from the PowerShell
        if: runner.os == 'Windows'
        shell: powershell
        run: Write-Host "Windows PowerShell is greeting"
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setting up correct Python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python package and requirements
        run: |
          python -m pip install .
          python -m pip install -r requirements-dev.txt

      - name: Run Python test
        run: |
          pytest
